// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Pick the database engine at deploy time. Default is SQLite (local dev).
// Set DB_PROVIDER=postgresql (together with a postgres:// DATABASE_URL) for
// hosting on PostgreSQL. The data model lives only in prisma/schema.prisma;
// schema.postgres.prisma is generated from it via `npm run db:pg:sync`.
const isPostgres = process.env["DB_PROVIDER"] === "postgresql";

export default defineConfig({
  schema: isPostgres
    ? "prisma/schema.postgres.prisma"
    : "prisma/schema.prisma",
  migrations: {
    path: isPostgres ? "prisma/migrations-postgres" : "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
